name: Deploy

on: 
  push:
    branches: [main]

jobs:
  
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Testing the project"
      - name: Using Node.js 20.13.1
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test
      - run: echo "Tests finished!"

  trigger_webhook:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Trigger Vercel Webhook
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_IPxtZHnrPtkXxJMKssIeEXbf0PE5/tlP6fNwAdb