name: Deploy

on: 
  push:
    branches: [main]

jobs:
  
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Testing the project"
      - name: Using Node.js 20.13.1
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test
      - run: echo "Tests finished!"

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}  # Check if the test job was successful
    steps:
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}